### ISSUE TITLE
Wiping by one controller with another with the same names from different paths

### ISSUE THREAD

**Issue by sergeks** [hexarc-software/hexarc-pact#2]
When we have controllers with the same name , but from different paths, the Pact generates single client interface file in the consumer. The generated code is strangely sticky and doesn't compile.

Sample:
(in schema)
namespace : "Rpm.Api.Controllers.App"
name : "PatientsController"
path : "/App/Patients"

namespace : "Rpm.Api.Controllers.Admin"
name : "PatientsController"
path : "/Admin/Patients"

(in generated 'api.ts')
...
import { PatientsController } from "./controllers/patients_controller";
import { PatientsController } from "./controllers/patients_controller";
...

**Comment by shadeglare** [comment]
Works as intended, name collisions must be handled be the `PactScope` attribute according to a consumer's needs.
